// Code generated by "stringer -type=Word"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOP-0]
	_ = x[HLT-1]
	_ = x[PUSH-2]
	_ = x[ZERO-3]
	_ = x[DROP-4]
	_ = x[DUP-5]
	_ = x[SWAP-6]
	_ = x[ADD-7]
	_ = x[SUB-8]
	_ = x[MUL-9]
	_ = x[DIV-10]
	_ = x[INC-11]
	_ = x[DEC-12]
	_ = x[AND-13]
	_ = x[OR-14]
	_ = x[XOR-15]
	_ = x[EQ-16]
	_ = x[NOT_EQ-17]
	_ = x[EQ_GREAT-18]
	_ = x[GREAT-19]
	_ = x[EQ_LESS-20]
	_ = x[LESS-21]
	_ = x[JMPC-22]
	_ = x[STORE-23]
	_ = x[STORE_ABS-24]
	_ = x[LOAD-25]
	_ = x[LOAD_ABS-26]
	_ = x[GET_RSP-27]
	_ = x[INC_RSP-28]
	_ = x[SET_RSP-29]
	_ = x[GET_RBP-30]
	_ = x[INC_RBP-31]
	_ = x[SET_RBP-32]
	_ = x[GET_PC-33]
	_ = x[SET_PC-34]
	_ = x[CALL-35]
	_ = x[RET-36]
}

const _Word_name = "NOPHLTPUSHZERODROPDUPSWAPADDSUBMULDIVINCDECANDORXOREQNOT_EQEQ_GREATGREATEQ_LESSLESSJMPCSTORESTORE_ABSLOADLOAD_ABSGET_RSPINC_RSPSET_RSPGET_RBPINC_RBPSET_RBPGET_PCSET_PCCALLRET"

var _Word_index = [...]uint8{0, 3, 6, 10, 14, 18, 21, 25, 28, 31, 34, 37, 40, 43, 46, 48, 51, 53, 59, 67, 72, 79, 83, 87, 92, 101, 105, 113, 120, 127, 134, 141, 148, 155, 161, 167, 171, 174}

func (i Word) String() string {
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
