// Code generated by "stringer -type=Word"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOP-0]
	_ = x[HLT-1]
	_ = x[PUSH-2]
	_ = x[ZERO-3]
	_ = x[DROP-4]
	_ = x[DUP-5]
	_ = x[SWAP-6]
	_ = x[ADD-7]
	_ = x[SUB-8]
	_ = x[MUL-9]
	_ = x[DIV-10]
	_ = x[INC-11]
	_ = x[DEC-12]
	_ = x[MAX-13]
	_ = x[MIN-14]
	_ = x[ABS-15]
	_ = x[AND-16]
	_ = x[OR-17]
	_ = x[XOR-18]
	_ = x[EQ-19]
	_ = x[NOT_EQ-20]
	_ = x[EQ_GREAT-21]
	_ = x[GREAT-22]
	_ = x[EQ_LESS-23]
	_ = x[LESS-24]
	_ = x[JMPC-25]
	_ = x[STORE-26]
	_ = x[STORE_ABS-27]
	_ = x[LOAD-28]
	_ = x[LOAD_ABS-29]
	_ = x[GET_RSP-30]
	_ = x[INC_RSP-31]
	_ = x[SET_RSP-32]
	_ = x[GET_RBP-33]
	_ = x[INC_RBP-34]
	_ = x[SET_RBP-35]
	_ = x[GET_PC-36]
	_ = x[SET_PC-37]
	_ = x[CALL-38]
	_ = x[RET-39]
}

const _Word_name = "NOPHLTPUSHZERODROPDUPSWAPADDSUBMULDIVINCDECMAXMINABSANDORXOREQNOT_EQEQ_GREATGREATEQ_LESSLESSJMPCSTORESTORE_ABSLOADLOAD_ABSGET_RSPINC_RSPSET_RSPGET_RBPINC_RBPSET_RBPGET_PCSET_PCCALLRET"

var _Word_index = [...]uint8{0, 3, 6, 10, 14, 18, 21, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 57, 60, 62, 68, 76, 81, 88, 92, 96, 101, 110, 114, 122, 129, 136, 143, 150, 157, 164, 170, 176, 180, 183}

func (i Word) String() string {
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
