// Code generated by "stringer -type=Word"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-0]
	_ = x[NOP-1]
	_ = x[EMIT-2]
	_ = x[PUSH-3]
	_ = x[ZERO-4]
	_ = x[DUP-5]
	_ = x[CDUP-6]
	_ = x[DROP-7]
	_ = x[SWAP-8]
	_ = x[ADD-9]
	_ = x[SUB-10]
	_ = x[MUL-11]
	_ = x[DIV-12]
	_ = x[INC-13]
	_ = x[DEC-14]
	_ = x[MAX-15]
	_ = x[MIN-16]
	_ = x[ABS-17]
	_ = x[MOD-18]
	_ = x[AND-19]
	_ = x[OR-20]
	_ = x[XOR-21]
	_ = x[NOT-22]
	_ = x[EQ-23]
	_ = x[NOT_EQ-24]
	_ = x[EQ_GREAT-25]
	_ = x[GREAT-26]
	_ = x[EQ_LESS-27]
	_ = x[LESS-28]
	_ = x[JMPC-29]
	_ = x[CALL-30]
	_ = x[RET-31]
	_ = x[STORE-32]
	_ = x[STORE_ABS-33]
	_ = x[LOAD-34]
	_ = x[LOAD_ABS-35]
	_ = x[GET_RSP-36]
	_ = x[INC_RSP-37]
	_ = x[SET_RSP-38]
	_ = x[GET_RBP-39]
	_ = x[INC_RBP-40]
	_ = x[SET_RBP-41]
	_ = x[GET_PC-42]
	_ = x[SET_PC-43]
}

const _Word_name = "HLTNOPEMITPUSHZERODUPCDUPDROPSWAPADDSUBMULDIVINCDECMAXMINABSMODANDORXORNOTEQNOT_EQEQ_GREATGREATEQ_LESSLESSJMPCCALLRETSTORESTORE_ABSLOADLOAD_ABSGET_RSPINC_RSPSET_RSPGET_RBPINC_RBPSET_RBPGET_PCSET_PC"

var _Word_index = [...]uint8{0, 3, 6, 10, 14, 18, 21, 25, 29, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 68, 71, 74, 76, 82, 90, 95, 102, 106, 110, 114, 117, 122, 131, 135, 143, 150, 157, 164, 171, 178, 185, 191, 197}

func (i Word) String() string {
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
