// Code generated by "stringer -type=Op"; DO NOT EDIT.

package fcpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-0]
	_ = x[NOP-1]
	_ = x[EMIT-2]
	_ = x[PERIOD-3]
	_ = x[PUSH-4]
	_ = x[PUSH_B-5]
	_ = x[ZERO-6]
	_ = x[DUP-7]
	_ = x[DROP-8]
	_ = x[SWAP-9]
	_ = x[OVER-10]
	_ = x[ROT-11]
	_ = x[PICK-12]
	_ = x[ROLL-13]
	_ = x[DEPTH-14]
	_ = x[TO_R-15]
	_ = x[R_FROM-16]
	_ = x[R_FETCH-17]
	_ = x[ADD-18]
	_ = x[SUB-19]
	_ = x[MUL-20]
	_ = x[DIV-21]
	_ = x[MAX-22]
	_ = x[MIN-23]
	_ = x[ABS-24]
	_ = x[MOD-25]
	_ = x[LSHIFT-26]
	_ = x[RSHIFT-27]
	_ = x[AND-28]
	_ = x[OR-29]
	_ = x[XOR-30]
	_ = x[NOT-31]
	_ = x[EQ-32]
	_ = x[NE-33]
	_ = x[GE-34]
	_ = x[GT-35]
	_ = x[LE-36]
	_ = x[LT-37]
	_ = x[JNZ-38]
	_ = x[JZ-39]
	_ = x[JMP-40]
	_ = x[CALL-41]
	_ = x[RET-42]
	_ = x[STORE-43]
	_ = x[STORE_B-44]
	_ = x[FETCH-45]
	_ = x[FETCH_B-46]
	_ = x[PUSHRSP-47]
	_ = x[POPRSP-48]
	_ = x[PUSHRBP-49]
	_ = x[POPRBP-50]
	_ = x[PUSHPC-51]
}

const _Op_name = "HLTNOPEMITPERIODPUSHPUSH_BZERODUPDROPSWAPOVERROTPICKROLLDEPTHTO_RR_FROMR_FETCHADDSUBMULDIVMAXMINABSMODLSHIFTRSHIFTANDORXORNOTEQNEGEGTLELTJNZJZJMPCALLRETSTORESTORE_BFETCHFETCH_BPUSHRSPPOPRSPPUSHRBPPOPRBPPUSHPC"

var _Op_index = [...]uint8{0, 3, 6, 10, 16, 20, 26, 30, 33, 37, 41, 45, 48, 52, 56, 61, 65, 71, 78, 81, 84, 87, 90, 93, 96, 99, 102, 108, 114, 117, 119, 122, 125, 127, 129, 131, 133, 135, 137, 140, 142, 145, 149, 152, 157, 164, 169, 176, 183, 189, 196, 202, 208}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
