// Code generated by "stringer -type=Word"; DO NOT EDIT.

package fcpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-65536]
	_ = x[NOP-65537]
	_ = x[EMIT-65538]
	_ = x[PERIOD-65539]
	_ = x[PUSH-65540]
	_ = x[ZERO-65541]
	_ = x[DUP-65542]
	_ = x[CDUP-65543]
	_ = x[DROP-65544]
	_ = x[SWAP-65545]
	_ = x[OVER-65546]
	_ = x[ROT-65547]
	_ = x[PICK-65548]
	_ = x[ROLL-65549]
	_ = x[DEPTH-65550]
	_ = x[TO_R-65551]
	_ = x[R_FROM-65552]
	_ = x[R_FETCH-65553]
	_ = x[ADD-65554]
	_ = x[SUB-65555]
	_ = x[MUL-65556]
	_ = x[DIV-65557]
	_ = x[ADD_ONE-65558]
	_ = x[SUB_ONE-65559]
	_ = x[MAX-65560]
	_ = x[MIN-65561]
	_ = x[ABS-65562]
	_ = x[MOD-65563]
	_ = x[AND-65564]
	_ = x[OR-65565]
	_ = x[XOR-65566]
	_ = x[NOT-65567]
	_ = x[EQ-65568]
	_ = x[NOT_EQ-65569]
	_ = x[EQ_GREAT-65570]
	_ = x[GREAT-65571]
	_ = x[EQ_LESS-65572]
	_ = x[LESS-65573]
	_ = x[JCC-65574]
	_ = x[JMP-65575]
	_ = x[CALL-65576]
	_ = x[RET-65577]
	_ = x[STORE-65578]
	_ = x[FETCH-65579]
	_ = x[GET_RSP-65580]
	_ = x[INC_RSP-65581]
	_ = x[SET_RSP-65582]
	_ = x[GET_RBP-65583]
	_ = x[INC_RBP-65584]
	_ = x[SET_RBP-65585]
	_ = x[GET_PC-65586]
	_ = x[SET_PC-65587]
}

const _Word_name = "HLTNOPEMITPERIODPUSHZERODUPCDUPDROPSWAPOVERROTPICKROLLDEPTHTO_RR_FROMR_FETCHADDSUBMULDIVADD_ONESUB_ONEMAXMINABSMODANDORXORNOTEQNOT_EQEQ_GREATGREATEQ_LESSLESSJCCJMPCALLRETSTOREFETCHGET_RSPINC_RSPSET_RSPGET_RBPINC_RBPSET_RBPGET_PCSET_PC"

var _Word_index = [...]uint8{0, 3, 6, 10, 16, 20, 24, 27, 31, 35, 39, 43, 46, 50, 54, 59, 63, 69, 76, 79, 82, 85, 88, 95, 102, 105, 108, 111, 114, 117, 119, 122, 125, 127, 133, 141, 146, 153, 157, 160, 163, 167, 170, 175, 180, 187, 194, 201, 208, 215, 222, 228, 234}

func (i Word) String() string {
	i -= 65536
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i+65536), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
