// Code generated by "stringer -type=Word"; DO NOT EDIT.

package fcpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-65536]
	_ = x[NOP-65537]
	_ = x[EMIT-65538]
	_ = x[PERIOD-65539]
	_ = x[PUSH-65540]
	_ = x[ZERO-65541]
	_ = x[DUP-65542]
	_ = x[CDUP-65543]
	_ = x[DROP-65544]
	_ = x[SWAP-65545]
	_ = x[OVER-65546]
	_ = x[ROT-65547]
	_ = x[DEPTH-65548]
	_ = x[ADD-65549]
	_ = x[SUB-65550]
	_ = x[MUL-65551]
	_ = x[DIV-65552]
	_ = x[ADD_ONE-65553]
	_ = x[SUB_ONE-65554]
	_ = x[MAX-65555]
	_ = x[MIN-65556]
	_ = x[ABS-65557]
	_ = x[MOD-65558]
	_ = x[AND-65559]
	_ = x[OR-65560]
	_ = x[XOR-65561]
	_ = x[NOT-65562]
	_ = x[EQ-65563]
	_ = x[NOT_EQ-65564]
	_ = x[EQ_GREAT-65565]
	_ = x[GREAT-65566]
	_ = x[EQ_LESS-65567]
	_ = x[LESS-65568]
	_ = x[JCC-65569]
	_ = x[JMP-65570]
	_ = x[CALL-65571]
	_ = x[RET-65572]
	_ = x[STORE-65573]
	_ = x[STORE_ABS-65574]
	_ = x[LOAD-65575]
	_ = x[LOAD_ABS-65576]
	_ = x[GET_RSP-65577]
	_ = x[INC_RSP-65578]
	_ = x[SET_RSP-65579]
	_ = x[GET_RBP-65580]
	_ = x[INC_RBP-65581]
	_ = x[SET_RBP-65582]
	_ = x[GET_PC-65583]
	_ = x[SET_PC-65584]
}

const _Word_name = "HLTNOPEMITPERIODPUSHZERODUPCDUPDROPSWAPOVERROTDEPTHADDSUBMULDIVADD_ONESUB_ONEMAXMINABSMODANDORXORNOTEQNOT_EQEQ_GREATGREATEQ_LESSLESSJCCJMPCALLRETSTORESTORE_ABSLOADLOAD_ABSGET_RSPINC_RSPSET_RSPGET_RBPINC_RBPSET_RBPGET_PCSET_PC"

var _Word_index = [...]uint8{0, 3, 6, 10, 16, 20, 24, 27, 31, 35, 39, 43, 46, 51, 54, 57, 60, 63, 70, 77, 80, 83, 86, 89, 92, 94, 97, 100, 102, 108, 116, 121, 128, 132, 135, 138, 142, 145, 150, 159, 163, 171, 178, 185, 192, 199, 206, 213, 219, 225}

func (i Word) String() string {
	i -= 65536
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i+65536), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
